services:
  postgresql:    
    image: postgres:16-alpine
    env_file:
      - .env 
    command: ['postgres', '-c', 'wal_level=logical']
    container_name: postgresql    
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes: 
      - postgres_data:/var/lib/postgresql/data

  jeager:
    image: jaegertracing/jaeger:2.6.0
    container_name: jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "5778:5778"
      - "9411:9411"
  
volumes:
  postgres_data: