services:
  postgresql:    
    image: postgres:16-alpine
    env_file:
      - .env 
    command: ['postgres', '-c', 'wal_level=logical']
    container_name: postgresql    
    ports:
      - "5432:5432"
    networks:
      - flavor_food
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes: 
      - postgres_data:/var/lib/postgresql/data

  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgresql
    volumes:
      - ./pgadmin_config/servers.json:/pgadmin4/servers.json
    entrypoint:
      - "/bin/sh"
      - "-c"
      - |
        mkdir -p /var/lib/pgadmin/storage/admin_example.com/
        cp /pgadmin4/servers.json /var/lib/pgadmin/storage/admin_example.com/servers.json
        /entrypoint.sh

  jeager:
    image: jaegertracing/jaeger:2.6.0
    container_name: jaeger
    hostname: jaeger
    ports:
      - "16686:16686"
      - "8888:8888"
      - "8889:8889"
      - "4317:4317"
      - "4318:4318"
    networks:
      flavor_food:
        aliases: [spm_metrics_source]
    volumes:
      - ./observability/config-spm.yaml:/etc/jaeger/config.yml
      - ./observability/jaeger-ui.json:/etc/jaeger/jaeger-ui.json"
    command: ["--config", "/etc/jaeger/config.yml"]
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    volumes:
      - "./observability/prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - flavor_food
    ports:
      - "9090:9090"

volumes:
  postgres_data:

networks:
  flavor_food: