name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # - name: Find all folders with Dockerfile
      #   id: folders
      #   run: |
      #     echo "services<<EOF" >> $GITHUB_OUTPUT
      #     find . -mindepth 1 -maxdepth 1 -type d | while read dir; do
      #       if [ -f "$dir/Dockerfile" ]; then
      #         echo $(basename "$dir") >> $GITHUB_OUTPUT
      #       fi
      #     done
      #     echo "EOF" >> $GITHUB_OUTPUT

      # - name: Build and Push Docker Images
      #   run: |
      #     for service in $(find . -mindepth 1 -maxdepth 1 -type d); do
      #       name=$(basename "$service")
      #       if [ -f "$service/Dockerfile" ]; then
      #         IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/$name"
      #         TAG=$(echo $GITHUB_SHA | cut -c1-7)
      #         echo "Building $IMAGE_NAME:$TAG"
      #         docker build -t "$IMAGE_NAME:$TAG" "$service"
      #         docker push "$IMAGE_NAME:$TAG"
      #       fi
      #     done
